### ISSUE TITLE
Designing basic interfaces

### ISSUE THREAD

**Issue by AdrianSchneble** [PixelMaster98/GridEngine#1]
We're gonna have to develop some basic interfaces, so we can get coding.
You got about an hour this evening @TheKleopiNetwork?

**Comment by TheKleopiNetwork** [comment]
Yes. Id rather communicate via Discord tho

**Comment by AdrianSchneble** [comment]
For voice chat etc., sure thing. I just figured we'd use github's issue feature for distributing tasks, seeing as that is its whole purpose.
